name:  Build and deploy on prod

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - run: gem update --system

    - run: gem install jekyll 

    - run: jekyll build
 
    - uses: actions/upload-artifact@v1
      with:
        name: aca-workshop
        path: _site
 
    - uses: tibor19/static-website-deploy@v1
      with:
        enabled-static-website: 'true'
        folder: '_site'
        connection-string: ${{ secrets.CONNECTION_STRING }}
